#! /bin/sh

/bin/mount -a

mount -t tmpfs tmpfs /dev 
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug 
mdev -s
mount -t jffs2 /dev/mtdblock0 /mnt
if [ $? -eq 0 ];then
cp -a -r /mnt/bin/* /sbin/
fi
